### ISSUE TITLE
Shriekers have an inventory tab

### ISSUE THREAD

**Issue by baobuh** [Andrew6rant/InventoryTabs#33] opened 2022-07-08 05:04 UTC
Shriekers are not chests but they still have their own tabs, I think this is a bug

**Comment by Andrew6rant** [comment] 2022-07-16 21:42
What version of InventoryTabs are you using? This should've been fixed in 0.7.0

**Comment by Andrew6rant** [comment] 2022-07-19 03:07
I'm going to close this issue now that 0.8.0 is released because it is fixed. Feel free to reopen this if you can reproduce the issue using 0.7.0 or 0.8.0.

**Closed as completed by Andrew6rant** 2022-07-19 03:07 UTC
