### ISSUE TITLE
1.18.2 Compatibility issues

### ISSUE THREAD

**Issue by stevened7246** [Andrew6rant/InventoryTabs#12] opened 2022-04-24 10:50 UTC
Already using the latest mod but not working in multiplayer
Multiplayer game log
[Server] [18:45:00] [Server thread/WARN]: Ignoring UseItemOnPacket from [playername]: Location (556.1292922496796, 63.875, -1094.0584033727646) too far away from hit block class_2338{x=559, y=63, z =-1096}.

**Comment by Julienraptor01** [comment] 2022-04-25 21:38
The problem isn't that it's not working it's just that you were too far from the chest and the server decide to ignore the action.

**Comment by stevened7246** [comment] 2022-04-28 17:25
> 問題不在於它不起作用，而在於您離胸部太遠而服務器決定忽略該動作。

But my situation is the same as #4

**Comment by Andrew6rant** [comment] 2022-06-24 04:33
Fixed in version 0.4.5. Sorry for the delay, I wasn't getting notifications for this repo

**Closed as completed by Andrew6rant** 2022-06-24 04:33 UTC
